[package]
name = "ci-fails"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde_json = "1.0.34"
quicli = "0.4"
structopt = "0.2"
regex = "1.1.0"
lazy_static = "1.2.0"
